name: ESB BLE feasibility
on:
  push:
    branches: [right_left_dongle_ble]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@9ebbeff0a8b69a42f14aec022cdf16c7a107b9e0
    with:
      build_matrix_path: build-crypto-probe.yaml
      archive_name: probe-firmware-not-for-flashing

